## Basic Configuration
baseURL = "/"
languageCode = "en"
title = "Trenton Pulsipher"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Trenton Pulsipher"
    title = "Title"
    description = "Data Scientist"
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    # highlightjsstyle = "github"
    # please choose either GraphComment or Disqus
    # GraphCommentId = "your-graph-comment-id" 

## Social Accounts
[params.social]
    github = "trentonpulsipher"
#    github = "HSPS-DataScience"
#    instagram = "<username>"
#    xing = "<username>"
    linkedin = "tcpulsipher"
#    twitter = "<username>"
#    facebook = "<username>"
#    stackoverflow = "<username>"
    email = "tcpulsipher@hotmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 200
    url = "/resume/"

